language: bash
python:
    - 3.6
    - 3.7

script:
- cd src/
- ./get_raw.sh test_shell 2015 1 1
- rm -rf test_shell
- ./get_raw.sh 2015 1 1

notifications:
  email:
    on_success: never
    on_failure: never
