options:
    limit_rows     : True     # specifies whether to only read the first ``max_rows`` of each csv
    max_rows       : 100000   # set number of rows to read of each CSV file since reading > 3 GB is going to take forever
    # when ``bound_lon`` or ``bound_lat`` is true, the boundaries are read from ``grid_params``
    bound_lon      : False    # specifies whether to use specified hard longitude boundaries instead of inferring them
    bound_lat      : True     # specifies whether to use specified hard latitude boundaries instead of inferring them
    # when ``bound_time`` or ``bound_zone`` is true, the boundaries are read from ``meta_params``
    bound_time     : True     # specifies whether to bound the times considered
    bound_zone     : True     # specifies whether to bound the zones being read
    interp_actions : True     # specifies whether to interpolate actions if state transitions are not adjacent, otherwise actions can be arbitrarily large
    allow_diag     : False    # when interp_actions is true, specifies whether to allow for diagonal grid actions or not
    append_coords  : False    # specifies whether to add raw latitude, longitude values as columns to the output csv
    prec_coords    : 3        # the number of decimal places to round each coordinate to
    min_states     : 2        # set minimum number of states in a trajectory necessary to qualify it for the output file

directories:
    in_dir_path  : ./  # specifies the directory where input data is located
    in_dir_data  : AIS_ASCII_by_UTM_Month/  # specifies the folder name containing all the data in the input directory
    out_dir_path : ./  # specifies the directory where output data files should be written
    out_dir_file : ais_data_output.csv  # specifies output file name (should be .csv)

# specifies the metadata bounds (inclusive) for what data to consider
# time bounds go from min_year/min_month - max_year/max_month, not just some month range of each valid year
meta_params:
    # the earliest time (inclusive) that will be considered
    # data are available until January 2015
    min_year  : 2015
    min_month : 1
    # the latest time (inclusive) that will be considered
    # data are available until December 2017
    max_year  : 2017
    max_month : 12
    # the range of zones (inclusive) that will be considered
    # zone description: 1 - 9 -> Alaska, 4 - 5 -> Hawaii, 9 - 20 -> continental US
    # data are available for zones 1 - 20, but see ``get_raw.sh`` for more information
    min_zone  : 15
    max_zone  : 20

# this will track the minimum and maximum latitudes and longitudes in the dataset if bound_lat and bound_lon are False
# otherwise, grid_params specifies the grid boundaries in degrees.
grid_params:
    min_lon   : -76.0  # the minimum longitude that will be considered
    max_lon   : -72.0  # the maximum longitude that will be considered
    min_lat   : 25.0   # the minimum latitude that will be considered
    max_lat   : 50.0   # the maximum latitude that will be considered
    num_cols  : 0      # the number of columns in the final grid, which will be automatically calculated by the script
    grid_len  : 0.5    # the length of one side of one grid square, in degrees

