options:
    limit_rows     : True     # specifies whether to only read the first MAX_ROWS of each csv
    bound_lon      : False    # specifies whether to use specified hard longitude boundaries instead of inferring them
    bound_lat      : True     # specifies whether to use specified hard latitude boundaries instead of inferring them
    bound_time     : True     # specifies whether to bound the times considered
    bound_zone     : True     # specifies whether to bound the zones being read
    interp_actions : True     # specifies whether to interpolate actions if state transitions are not adjacent, otherwise actions can be arbitrarily large
    allow_diag     : False    # when interp_actions is true, specifies whether to allow for diagonal grid actions or not
    MAX_ROWS       : 1000000  # set number of rows to read of each CSV file since reading > 3 GB is going to take forever
    MIN_STATES     : 2        # set minimum number of states in a trajectory necessary to qualify it for the output file

directories:
    in_dir_path  : ./  # specifies the directory where input data is located
    in_dir_data  : AIS_ASCII_by_UTM_Month/  # specifies the folder name containing all the data in the input directory
    out_dir_path : ./  # specified the directory where output data files should be written
    out_dir_file : ais_data_output.csv  # specifies output file name (should be .csv)
    # out_meta    : ais_meta_output.csv  # specifies output file for grid metadata

# ais csv file row indices for input data of interest
csv_indices:
    mmsi : 0
    time : 1
    lon  : 3
    lat  : 2

# specifies the metadata bounds (inclusive) for what data to consider
# time bounds go from min_year/min_month - max_year/max_month, not just some month range of each valid year
meta_params:
    min_year  : 2017
    min_month : 1
    max_year  : 2017
    max_month : 1
    min_zone  : 18
    max_zone  : 18

# this will track the minimum and maximum latitudes and longitudes in the dataset if bound_lat and bound_lon are False
# otherwise, grid_params specifies the grid boundaries in degrees.
grid_params:
    min_lon   : -76.0
    max_lon   : -72.0
    min_lat   : 35.0
    max_lat   : 42.0
    num_cols  : 0
    grid_len  : 1.0

